name: Tag

on:
  push:
    tags:
    - '*'
    - '!*/*'

jobs:
  check_version:
    name: Tag/Check version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag version
        id: extract_tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Extract version from file
        id: extract_version
        run: |
          VERSION=$(grep '__version__' ./docker2mqtt | sed -E 's/__version__ = "(.*)"/\1/')
          echo "FILE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compare versions
        run: |
          if [ "$TAG_VERSION" != "$FILE_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match file version ($FILE_VERSION)."
            exit 1
          else
            echo "Tag version ($TAG_VERSION) matches file version ($FILE_VERSION)."
          fi    
  publish:
    name: Tag/Publish
    needs: check_version
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/miaucl/docker2mqtt
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: miaucl
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

  release:
    name: Tag/Release
    needs: publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Get version
      id: version
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.version.outputs.version }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}